---
sidebar: sidebar 
permalink: learn-well-architected-dashboard.html 
keywords: well-architected, best practices, well-architected system, best practices, well-architected framework, well-architected configurations, system management, system optimization, system configuration, system analysis 
summary: NetApp Console scannt Systemkonfigurationen auf Zuverlässigkeit, Sicherheit, operative Exzellenz, Kostenoptimierung und Leistungseffizienz und liefert Erkenntnisse und Empfehlungen, die Ihnen helfen, operative Exzellenz zu erreichen. 
---
= Informationen zum gut gestalteten Dashboard in der NetApp Console
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Console unterstützt bei der Wartung und dem Betrieb zuverlässiger, sicherer, effizienter und kostengünstiger Konfigurationen, die mit den bewährten Frameworks für den verwendeten Speichertyp übereinstimmen. Das Well-Architected-Dashboard bietet eine einheitliche Ansicht über Konten und Regionen hinweg, unterstützt Teams bei der Identifizierung und Priorisierung von Risiken und ermöglicht benutzerdefinierte Regeln für spezifische Anforderungen. Automatische tägliche Scans Ihrer Speichersystemkonfigurationen liefern Einblicke und Empfehlungen, um Ihre Speicherumgebungen zu optimieren.



[[how-it-works]]
== So funktioniert es

NetApp Console analysiert Ihre Konfigurationen täglich. Die Analyse liefert gut strukturierte Statusberichte, Einblicke und Empfehlungen.

Nach Abschluss der täglichen Analyse werden die Konfigurationen im Well-Architected-Dashboard der Bereitstellung als „optimiert“ oder „nicht optimiert“ angezeigt. Dort finden Sie die Gesamtoptimierungsbewertung, Konfigurationsprobleme nach Kategorie sowie eine Liste der Konfigurationsprobleme und Empfehlungen. Die Empfehlungen zu den Konfigurationsproblemen können überprüft werden. Einige Probleme können automatisch von der NetApp Console behoben werden, während andere ein manuelles Eingreifen erfordern. In diesem Fall stellt die NetApp Console detaillierte Anweisungen zur Verfügung, um bei der Umsetzung der empfohlenen Änderungen zu unterstützen.

Sie können die Analyse von Konfigurationen, die für Ihre Umgebungen nicht relevant sind, ausblenden. Dadurch werden unnötige Warnmeldungen und ungenaue Optimierungsergebnisse vermieden. Wenn die Analyse einer bestimmten Konfiguration ausgeblendet wird, schließt NetApp Console diese Konfiguration nicht in die Gesamtoptimierungsbewertung ein.



[[why-it-matters]]
== Warum es wichtig ist

NetApp Console wendet Best Practices für große Speicher-, Datenbank- und VMware-Umgebungen an, indem kontinuierliche Analysen mit Empfehlungseinblicken und Fehlerbehebungen kombiniert werden. Automatisierte Korrekturen, die in der NetApp Console angewendet werden, reduzieren menschliche Fehler, gewährleisten einheitliches Management und erhalten Leistung und Zuverlässigkeit Ihrer Systeminfrastrukturen.



[[supported-storage-systems]]
== Unterstützte Speichersysteme

Die folgenden Speichersysteme werden im Well-Architected Dashboard in der Console unterstützt:

* Amazon FSx for NetApp ONTAP
* Cloud Volumes ONTAP in Microsoft Azure




[[get-started-with-netapp-console-to-detect-and-fix-system-misconfigurations]]
== Mit der NetApp Console Systemfehlkonfigurationen erkennen und beheben

Um mit der NetApp Console zu beginnen, ist eine Registrierung, das Hinzufügen von Anmeldeinformationen und das Herstellen einer Verbindung erforderlich, um Ressourcen zu verwalten und Systemkonfigurationen zu optimieren.

link:http://docs.netapp.com/us-en/console-setup-admin/task-quick-start-standard-mode.html["Einstiegs-Workflow für die NetApp Console (SaaS-Anwendung)"^]



[[related-information]]
== Verwandte Informationen

* link:fsx/improve-configurations-fsx.html["Implementieren Sie gut strukturierte FSx for ONTAP Dateisysteme"^]
* link:cvo/improve-configurations-cvo.html["Gut strukturierte Cloud Volumes ONTAP Systeme implementieren"^]

