---
sidebar: sidebar 
permalink: learn-well-architected-dashboard.html 
keywords: well-architected, best practices, well-architected system, best practices, well-architected framework, well-architected configurations, system management, system optimization, system configuration, system analysis 
summary: Das übersichtliche Dashboard in NetApp Console scannt Systemkonfigurationen auf Zuverlässigkeit, Sicherheit, operative Exzellenz, Kostenoptimierung und Leistungseffizienz und liefert Erkenntnisse und Empfehlungen, die zur Erreichung operativer Exzellenz beitragen. 
---
= Informationen zum gut gestalteten Dashboard in der NetApp Console
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Workload Factory unterstützt bei der Wartung und dem Betrieb zuverlässiger, sicherer, effizienter und kostengünstiger Konfigurationen, die mit den bewährten Frameworks für den verwendeten Speichertyp übereinstimmen. Das Well-Architected-Dashboard in der NetApp Console bietet eine einheitliche Ansicht über Konten und Regionen hinweg, unterstützt Teams bei der Identifizierung und Priorisierung von Risiken und ermöglicht benutzerdefinierte Regeln für spezifische Anforderungen. Automatische tägliche Scans der Speichersystemkonfigurationen liefern Einblicke und Empfehlungen zur Optimierung der Speicherumgebungen.



[[how-it-works]]
== So funktioniert es

Workload Factory analysiert Ihre Konfigurationen täglich. Die Analyse liefert gut strukturierte Statusberichte, Erkenntnisse und Empfehlungen, um Ihre Speicherumgebungen zu optimieren.

Nach Abschluss der täglichen Analyse werden die Konfigurationen im Well-Architected-Dashboard als „optimiert“ oder „nicht optimiert“ angezeigt. Konfigurationsprobleme sind nach Kategorien des Well-Architected-Frameworks (Zuverlässigkeit, Sicherheit, operative Exzellenz, Kostenoptimierung und Leistungseffizienz) sowie als Liste von Konfigurationsproblemen und Empfehlungen aufgeführt. Workload Factory kann einige Probleme automatisch beheben, während andere Probleme manuelle Eingriffe erfordern. In diesem Fall enthält die Empfehlung detaillierte Anweisungen, die bei der Umsetzung der Änderungen unterstützen.

Sie können die Analyse von Konfigurationen, die für Ihre Umgebungen nicht relevant sind, ausblenden. Das Ausblenden von Konfigurationen vermeidet unnötige Warnmeldungen und ungenaue Optimierungsergebnisse.



[[why-it-matters]]
== Warum es wichtig ist

Workload Factory wendet Best Practices auf große Speicher-, Datenbank- und VMware-Umgebungen an, indem kontinuierliche Analysen mit Empfehlungseinblicken und Fehlerbehebung kombiniert werden. Automatisierte Fehlerbehebung reduziert menschliche Fehler, gewährleistet einheitliches Management und erhält Leistung und Zuverlässigkeit Ihrer Systeminfrastrukturen.



[[supported-storage-systems]]
== Unterstützte Speichersysteme

Das übersichtliche Dashboard in der Konsole unterstützt die folgenden Speichersysteme:

* Amazon FSx for NetApp ONTAP
* Cloud Volumes ONTAP in Microsoft Azure




[[get-started-with-netapp-console-to-detect-and-fix-system-misconfigurations]]
== Mit der NetApp Console Systemfehlkonfigurationen erkennen und beheben

Um mit der NetApp Console zu beginnen, ist eine Registrierung, das Hinzufügen von Anmeldeinformationen und das Herstellen einer Verbindung erforderlich, um Ressourcen zu verwalten und Systemkonfigurationen zu optimieren.

link:http://docs.netapp.com/us-en/console-setup-admin/task-quick-start-standard-mode.html["Einstiegs-Workflow für die NetApp Console (SaaS-Anwendung)"^]



[[related-information]]
== Verwandte Informationen

* link:fsx/improve-configurations-fsx.html["Implementieren Sie gut strukturierte FSx for ONTAP Dateisysteme"^]
* link:cvo/improve-configurations-cvo.html["Gut strukturierte Cloud Volumes ONTAP Systeme implementieren"^]

