---
sidebar: sidebar 
permalink: learn-well-architected-dashboard.html 
keywords: well-architected, best practices, well-architected system, best practices, well-architected framework, well-architected configurations, system management, system optimization, system configuration, system analysis 
summary: Das übersichtliche Dashboard in NetApp Console scannt Systemkonfigurationen auf Zuverlässigkeit, Sicherheit, operative Exzellenz, Kostenoptimierung und Leistungseffizienz und liefert Erkenntnisse und Empfehlungen, die zur Erreichung operativer Exzellenz beitragen. 
---
= Informationen zum gut gestalteten Dashboard in der NetApp Console
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Das übersichtliche Dashboard in NetApp Console unterstützt die Wartung und den Betrieb zuverlässiger, sicherer, effizienter und kostengünstiger Konfigurationen, die mit den bewährten Frameworks für den verwendeten Speichertyp übereinstimmen. Das Dashboard bietet eine einheitliche Ansicht über Konten und Regionen hinweg, unterstützt Teams bei der Identifizierung und Priorisierung von Risiken und ermöglicht benutzerdefinierte Regeln für spezifische Anforderungen. Automatische tägliche Scans der Speichersystemkonfigurationen liefern Erkenntnisse und Empfehlungen zur Optimierung der Speicherumgebungen.



[[how-it-works]]
== So funktioniert es

Das Well-Architected Dashboard analysiert Ihre Konfigurationen täglich. Die Analyse liefert Well-Architected-Status, Einblicke und Empfehlungen.

Nach Abschluss der täglichen Analyse werden die Konfigurationen im Well-Architected Dashboard als „optimiert“ oder „nicht optimiert“ angezeigt. Dort finden Sie die Gesamtoptimierungsbewertung, Konfigurationsprobleme nach Kategorie sowie eine Liste von Konfigurationsproblemen und Empfehlungen. Empfehlungen zu den Konfigurationsproblemen können eingesehen werden. Einige Probleme können automatisch durch das Well-Architected Dashboard behoben werden, während andere manuelle Eingriffe erfordern. In diesem Fall stellt das Well-Architected Dashboard detaillierte Anweisungen bereit, um die empfohlenen Änderungen umzusetzen.

Sie können die Analyse von Konfigurationen ausblenden, die für Ihre Umgebungen nicht relevant sind. Dadurch werden unnötige Warnmeldungen und ungenaue Optimierungsergebnisse vermieden. Wenn die Analyse einer bestimmten Konfiguration ausgeblendet wird, wird diese Konfiguration im Well-Architected Dashboard nicht in die Gesamtoptimierungsbewertung einbezogen.



[[why-it-matters]]
== Warum es wichtig ist

Das Well-Architected Dashboard in der NetApp Console wendet Best Practices auf große Storage-, Datenbank- und VMware-Umgebungen an, indem es kontinuierliche Bewertungen mit Empfehlungseinblicken und Fehlerbehebungen kombiniert. Automatisierte Fehlerbehebungen, die im Well-Architected Dashboard angewendet werden, reduzieren menschliche Fehler, gewährleisten einheitliches Management und erhalten Leistung und Zuverlässigkeit Ihrer Systeminfrastrukturen.



[[supported-storage-systems]]
== Unterstützte Speichersysteme

Das übersichtliche Dashboard in der Konsole unterstützt die folgenden Speichersysteme:

* Amazon FSx for NetApp ONTAP
* Cloud Volumes ONTAP in Microsoft Azure




[[get-started-with-netapp-console-to-detect-and-fix-system-misconfigurations]]
== Mit der NetApp Console Systemfehlkonfigurationen erkennen und beheben

Um mit der NetApp Console zu beginnen, ist eine Registrierung, das Hinzufügen von Anmeldeinformationen und das Herstellen einer Verbindung erforderlich, um Ressourcen zu verwalten und Systemkonfigurationen zu optimieren.

link:http://docs.netapp.com/us-en/console-setup-admin/task-quick-start-standard-mode.html["Einstiegs-Workflow für die NetApp Console (SaaS-Anwendung)"^]



[[related-information]]
== Verwandte Informationen

* link:fsx/improve-configurations-fsx.html["Implementieren Sie gut strukturierte FSx for ONTAP Dateisysteme"^]
* link:cvo/improve-configurations-cvo.html["Gut strukturierte Cloud Volumes ONTAP Systeme implementieren"^]

