---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, well-architected, well-architected dashboard, amazon fsx for netapp ontap, fsx for ontap, cloud volumes ontap, microsoft azure' 
summary: Informationen zu den Neuerungen im gut strukturierten Dashboard in der NetApp Console. 
---
= Was ist neu am gut strukturierten Dashboard in der NetApp Console
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Informationen zu den Neuerungen im gut strukturierten Dashboard in der NetApp Console.



[[17-august-2026]]
== 17. August 2026



[[fsx-for-ontap-support-in-the-well-architected-dashboard-in-netapp-console]]
=== FSx for ONTAP Unterstützung im Well-Architected Dashboard in der NetApp Console

Das gut strukturierte Dashboard in NetApp Console ist für Amazon FSx for NetApp ONTAP verfügbar.

* link:https://docs.netapp.com/us-en/console-well-architected/fsx/configuration-analysis-fsx.html["Informationen zur Konfigurationsanalyse für FSx für ONTAP"]




[[updated-configuration-names-for-fsx-for-ontap-in-the-well-architected-dashboard]]
=== Aktualisierte Konfigurationsnamen für FSx für ONTAP im Well-Architected Dashboard

Das übersichtliche Dashboard in NetApp Console enthält nun neue Speicherkonfigurationsnamen für FSx für ONTAP.

Die folgende Tabelle zeigt die alten Konfigurationsnamen und die entsprechenden neuen Konfigurationsnamen im Well-Architected Dashboard.

[cols="1,1"]
|===
| Alter Konfigurationsname | Neuer Konfigurationsname 


| Volumes-Backups planen | Volume Backups 


| SSD-Kapazitätsschwelle | SSD Kapazitätsreserve 


| Dateikapazitätsschwelle | Dateikapazitäts-Spielraum 


| Zuverlässigkeit der Langzeitaufbewahrungsdaten | Replikationsrichtlinienbezeichnungen 


| Geplante lokale Snapshots | Snapshot-Richtlinie 


| Unnötige Backups löschen | Ablauf der Sicherung 


| Unnötige Snapshots löschen | Snapshot-Ablauf 


| Nicht ausgelastete SSD-Kapazität | Überdimensionierte SSD-Kapazität 


| Inaktive Blockgeräte | Inaktive Blockgeräte (LUN) 


| Optimierung der Gesamtbetriebskosten durch das Tiering von Kaltdaten | Kaltdaten-Tiering 


| Bericht zur logischen Volumenkapazität | Host-sichtbare Kapazitätsberichterstattung 


| FlexGroup Volumenausgleich | Neu ausbalancieren von FlexGroup-Volumes 


| FlexVol Volumenausgleich | FlexVol Volumes neu verteilen 


| Schreibmodus für Cache-Beziehungen | FlexCache Schreibmodus 


| Cache-Volume-Größe optimieren | FlexCache Replika-Größe 


| Unbefugter Zugriff auf Volume | Unautorisierter Zugriff auf iSCSI Volumes 


| ARP/AI deaktiviert | Ransomware-Schutz (ARP/AI) 
|===


[[well-architected-issues-displayed-in-netapp-console-systems-page]]
=== Gut strukturierte Probleme werden auf der Seite „NetApp Console Systems“ angezeigt

Benachrichtigungen zu Architekturproblemen sind für Cloud Volumes ONTAP in Microsoft Azure auf der Seite „Storage management Systems“ in der NetApp Console verfügbar. Mit dieser Funktion lassen sich Konfigurationsprobleme in Cloud Volumes ONTAP-Systemen in Azure schnell erkennen und vom Hinweis aus zum Workloads well-architected Dashboard wechseln.



[[10-august-2026]]
== 10. August 2026



[[google-cloud-netapp-volumes-support-in-the-well-architected-dashboard]]
=== Google Cloud NetApp Volumes Unterstützung im Well-Architected Dashboard

Das NetApp Console Dashboard unterstützt jetzt Google Cloud NetApp Volumes. Speicheradministratoren können den Status ihrer Speicherpools und Konfigurationen einsehen, Empfehlungen zur Verbesserung von Effizienz, Kosten, Leistung, Zuverlässigkeit und Sicherheit erhalten sowie Maßnahmen zur Optimierung des Betriebs und zur Einhaltung bewährter Verfahren ergreifen.

Weitere Informationen zu link:https://docs.netapp.com/us-en/console-well-architected/gcnv/configuration-analysis-gcnv.html["Konfigurationsanalyse für Google Cloud NetApp Volumes"].



[[03-august-2026]]
== 03. August 2026



[[fix-dismiss-and-reactivate-configurations-for-cloud-volumes-ontap-in-microsoft-azure]]
=== Konfigurationen für Cloud Volumes ONTAP in Microsoft Azure beheben, verwerfen und reaktivieren

Das übersichtliche Dashboard in NetApp Console bietet jetzt die Möglichkeit, Konfigurationsempfehlungen für Ihre Cloud Volumes ONTAP Systeme zu beheben.

Sie können auch eine oder mehrere Konfigurationen von der Analyse der optimalen Architektur ausschließen. Dadurch ist es möglich, bestimmte Konfigurationen zu ignorieren, die für Ihre Umgebung nicht zutreffen.

Wenn Sie eine verworfene Konfiguration später wieder einbinden möchten, können Sie sie im Well-Architected Dashboard reaktivieren. Dadurch wird die Konfiguration in die Analyse zurückgeholt und es werden Empfehlungen und Korrekturen dafür bereitgestellt.

link:https://docs.netapp.com/us-en/console-well-architected/cvo/\improve-configurations-cvo.html["Konfigurationen für Cloud Volumes ONTAP in Microsoft Azure beheben, verwerfen und reaktivieren"]



[[20-july-2026]]
== 20. Juli 2026



[[introducing-the-well-architected-dashboard-in-netapp-console]]
=== Einführung des gut strukturierten Dashboards in der NetApp Console

Das übersichtliche Dashboard in der NetApp Console bietet eine zentrale Übersicht über Ihre Speichersysteme und Konfigurationen über alle Konten und Regionen hinweg. Das Dashboard liefert Einblicke und Empfehlungen, die zur Erreichung optimaler Betriebsabläufe beitragen. Der Well-Architected-Status Ihrer Konfigurationen, Konfigurationsprobleme, die nach den Säulen des Well-Architected-Frameworks für den von Ihnen verwendeten Speichertyp organisiert sind, sowie eine Liste von Konfigurationsproblemen und Empfehlungen werden angezeigt.

Erfahren Sie mehr über das link:https://docs.netapp.com/us-en/console-well-architected/learn-well-architected-dashboard.html["gut gestaltetes Dashboard"].

Das übersichtliche Dashboard in der Konsole ist verfügbar für link:https://docs.netapp.com/us-en/console-well-architected/cvo/configuration-analysis-cvo.html["Cloud Volumes ONTAP in Microsoft Azure."]



[[build-your-own-custom-rules]]
=== Eigene benutzerdefinierte Regeln erstellen

Benutzerdefinierte Regeln können in einfacher Sprache erstellt werden, damit Ihre Systeme den Standards Ihres Unternehmens und den NetApp Best Practices entsprechen. Die Regeln lassen sich mit einem Probelauf testen und anschließend für die Ausführung in Ihren Umgebungen einplanen.

https://docs.netapp.com/us-en/console-well-architected/learn-custom-rules.html["Weitere Informationen zu benutzerdefinierten Regeln"]
