---
sidebar: sidebar 
permalink: gcnv/configuration-analysis-gcnv.html 
keywords: configuration issues, issues, improve, analyze, storage configuration, recommendation, recommendations 
summary: NetApp Console analysiert regelmäßig die Konfigurationen der Speichersysteme, um festzustellen, ob Konfigurationsprobleme vorliegen. 
---
= Konfigurationsanalyse für Google Cloud NetApp Volumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Das übersichtliche Dashboard in NetApp Console überprüft regelmäßig die Einstellungen Ihres Speichersystems auf potenzielle Probleme. Wenn Probleme gefunden werden, werden diese angezeigt und es wird erläutert, wie sie behoben werden können, damit Ihre Speichersysteme eine optimale Leistung erbringen, Kosten kontrolliert werden und Best Practices sowohl im Standardmodus als auch im ONTAP Modus für Flex Unified Google Cloud NetApp Volumes Umgebungen eingehalten werden.

Zu den wichtigsten Fähigkeiten gehören:

* Tägliche Konfigurationsanalyse
* Automatische Validierung bewährter Verfahren für NetApp ONTAP Speichersysteme und Partner-Speicheranbieter
* Proaktive Beobachtbarkeit
* Erkenntnisse in die Praxis umsetzen




[[analysis-requirements]]
== Analyseanforderungen

Für eine vollständige Analyse des Speicherpools sind die folgenden Schritte erforderlich:

* link:https://docs.netapp.com/us-en/storage-management-google-cloud-netapp-volumes/task-create-system.html["Ihr Google Cloud NetApp Volumes System zur NetApp Console hinzufügen"^].
* Die Berechtigungen _Anzeigen, Planen und Analysieren_ müssen in Ihrem Google Cloud-Konto vergeben sein.
+
link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["Informationen dazu, wie einem Google Cloud Konto Berechtigungen gewährt werden"^]





[[best-practices-and-recommendations-for-storage-workloads]]
== Bewährte Verfahren und Empfehlungen für Speicher-Workloads

Workload Factory bewertet Speicherkonfigurationen anhand von Best Practices für Storage und ONTAP sowie des Google Cloud Well-Architected Framework. Die Bewertung empfiehlt außerdem Verbesserungen für Google Cloud NetApp Volumes Default-mode-Ressourcen und Flex Unified-Ressourcen, die über den ONTAP API proxy endpoint erkannt wurden.

Die Well-Architected-Analyse kategorisiert Konfigurationen anhand der folgenden Säulen des Frameworks: _Zuverlässigkeit_ und _operative Exzellenz_. Die Bewertungsergebnisse können einen Moduswert von _Default-mode_ oder _ONTAP-mode_ enthalten.



[[reliability]]
=== Zuverlässigkeit

Zuverlässigkeit gewährleistet, dass Arbeitslasten ihre beabsichtigten Funktionen korrekt und konsistent erfüllen, selbst wenn es zu Störungen kommt.

* *Snapshot Policy*
+
Planen Sie lokale Snapshots für effiziente Datensicherung und schnelle Wiederherstellung. Snapshots sind sofortige, zeitpunktgenaue Abbilder Ihrer Volumes.

* *SSD-Kapazitätsreserve*
+
Workload Factory empfiehlt, die SSD-Tier-Auslastung auf 80 % oder weniger zu halten. Einige Workloads benötigen möglicherweise zusätzlichen Kapazitätsspielraum und niedrigere Auslastungsziele. Wenn die empfohlene Reserve überschritten wird, steigt das Risiko von Leistungseinbußen und Serviceproblemen, insbesondere wenn die Kapazität nicht rechtzeitig erweitert wird. Diese Einstellung kann für einen oder mehrere Speicherpools ausgeblendet und bei Bedarf später wieder aktiviert werden.





[[operational-excellence]]
=== Operative Exzellenz

Operative Exzellenz konzentriert sich auf die Bereitstellung der optimalsten Architektur und des größten Geschäftswerts.

* *Freier Volumenkapazitätsspielraum*
+
Workload Factory empfiehlt, die Volume-Auslastung unter 80 % zu halten, um das Risiko von Speicherplatzengpässen zu minimieren. Wenn ein Volume schneller als erwartet wächst, könnte eine schnelle Erweiterung erforderlich sein. Dadurch kann das Risiko von Auswirkungen auf Anwendungen steigen, insbesondere bei plötzlichem oder sprunghaftem Wachstum. Dieses Risiko ist geringer, wenn Thin Provisioning und automatische Kapazitätsmanagement verwendet werden. Für ein oder mehrere Volumes kann diese Funktion deaktiviert und bei Bedarf später wieder aktiviert werden.



.Was kommt als Nächstes
link:improve-configurations-gcnv.html["Gut strukturierte Google Cloud NetApp Volumes Konfigurationen implementieren"]
