---
sidebar: sidebar 
permalink: fsx/configuration-analysis-fsx.html 
keywords: configuration issues, issues, improve, analyze, storage configuration, recommendation, recommendations 
summary: Das gut strukturierte Dashboard analysiert regelmäßig die Dateisystemkonfigurationen von FSx for ONTAP, um festzustellen, ob Konfigurationsprobleme vorliegen. 
---
= Konfigurationsanalyse für Amazon FSx für NetApp ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Das gut strukturierte Dashboard in der NetApp Console analysiert regelmäßig die Konfigurationen der Speichersysteme, um festzustellen, ob Konfigurationsprobleme mit Ihren Amazon FSx for NetApp ONTAP Dateisystemen vorliegen. Wenn Probleme festgestellt werden, zeigt das Dashboard an, welche Probleme bestehen, und erläutert, welche Änderungen erforderlich sind, damit Ihre Speichersysteme Spitzenleistung, Kosteneffizienz und die Einhaltung bewährter Verfahren erreichen.

Zu den wichtigsten Fähigkeiten gehören:

* Tägliche Konfigurationsanalyse
* Automatische Validierung bewährter Verfahren für NetApp ONTAP Speichersysteme und Partner-Speicheranbieter
* Proaktive Beobachtbarkeit
* Erkenntnisse in die Praxis umsetzen


Unaufgelöste Direktive in <stdin> - include::well-architected-workloads.adoc[]



[[analysis-requirements]]
== Analyseanforderungen

Für eine vollständige Dateisystemanalyse sind die folgenden Schritte erforderlich:

* link:https://docs.netapp.com/us-en/console-setup-admin/concept-agent-install-options.html#agent-console-deploy["Einen NetApp Console-Agenten bereitstellen"^] oder link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["einen Link verknüpfen"^] zur Einrichtung der Konnektivität zwischen dem Dateisystem und der NetApp Console.
* Gewähren Sie _view, planning, and analysis_-Berechtigungen in Ihrem AWS-Konto.
+
link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["Erfahren Sie, wie Sie einem AWS-Konto Berechtigungen erteilen"^]



Nicht aufgelöste Direktive in <stdin> - include::fsx-configurations.adoc[]

.Was kommt als Nächstes
link:improve-configurations-fsx.html["Gut strukturierte FSx for ONTAP Dateisystemkonfigurationen implementieren"]
