---
sidebar: sidebar 
permalink: fsx/configuration-analysis-fsx.html 
keywords: configuration issues, issues, improve, analyze, storage configuration, recommendation, recommendations 
summary: NetApp Console analysiert regelmäßig die Speichersystemkonfigurationen, um festzustellen, ob Konfigurationsprobleme vorliegen. 
---
= Konfigurationsanalyse für Amazon FSx für NetApp ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp Console analysiert regelmäßig die Konfigurationen der Speichersysteme, um festzustellen, ob Konfigurationsprobleme vorliegen. Wenn Probleme gefunden werden, zeigt NetApp Console an, worin diese bestehen, und erläutert, welche Änderungen erforderlich sind, damit die Speichersysteme optimale Leistung, Kosteneffizienz und die Einhaltung bewährter Verfahren erreichen.

Zu den wichtigsten Fähigkeiten gehören:

* Tägliche Konfigurationsanalyse
* Automatische Validierung bewährter Verfahren für NetApp ONTAP Speichersysteme und Partner-Speicheranbieter
* Proaktive Beobachtbarkeit
* Erkenntnisse in die Praxis umsetzen




[[how-it-works]]
== So funktioniert es

Workload Factory analysiert täglich Ihre Workloads, die auf Amazon FSx for NetApp ONTAP-Dateisystembereitstellungen laufen. Die Analyse liefert gut strukturierte Statusberichte, Einblicke und Empfehlungen.

Nach Abschluss der täglichen Analyse werden die Konfigurationen im Well-architected Dashboard für die Bereitstellung als „optimiert“ oder „nicht optimiert“ angezeigt. Dort finden Sie die Gesamtoptimierungsbewertung, Konfigurationsprobleme nach Kategorie sowie eine Liste der Konfigurationsprobleme und Empfehlungen. Die Empfehlungen zu den Konfigurationsproblemen können überprüft werden. Einige Probleme können automatisch von Workload Factory behoben werden, während andere eine manuelle Intervention erfordern. In diesem Fall stellt Workload Factory detaillierte Anweisungen bereit, um Ihnen bei der Umsetzung der empfohlenen Änderungen zu helfen.

Sie können die Analyse von Konfigurationen, die für Ihre Umgebungen nicht relevant sind, ausblenden. Dadurch werden unnötige Warnmeldungen und ungenaue Optimierungsergebnisse vermieden. Wenn Sie eine bestimmte Konfigurationsanalyse ausblenden, berücksichtigt Workload Factory die Konfiguration nicht in der Gesamtoptimierungsbewertung.



[[why-it-matters]]
== Warum es wichtig ist

Workload Factory wendet Best Practices auf große Speicher-, Datenbank- und VMware-Umgebungen an, indem kontinuierliche Analysen mit Empfehlungseinblicken und Fehlerbehebungen kombiniert werden. Automatisierte Korrekturen, die in der Workload Factory-Konsole angewendet werden, reduzieren menschliche Fehler, gewährleisten einheitliches Management und erhalten Leistung und Zuverlässigkeit über Ihre Workload-Infrastrukturen hinweg.



[[analysis-requirements]]
== Analyseanforderungen

Für eine vollständige Dateisystemanalyse sind die folgenden Schritte erforderlich:

* link:https://docs.netapp.com/us-en/console-setup-admin/concept-agent-install-options.html#agent-console-deploy["Einen NetApp Console-Agenten bereitstellen"^] oder link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["einen Link verknüpfen"^]. Konsolenagent und Link-Konnektivität ermöglichen es der NetApp Console, alle Dateisystemkonfigurationen wie Datenschutz und Leistung zu analysieren.
* Gewähren Sie _view, planning, and analysis_-Berechtigungen in Ihrem AWS-Konto.
+
link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["Erfahren Sie, wie Sie einem AWS-Konto Berechtigungen erteilen"^]





[[best-practices-and-recommendations-for-storage-workloads]]
== Bewährte Verfahren und Empfehlungen für Speicher-Workloads

Workload Factory bewertet Speicherkonfigurationen anhand von ONTAP Best Practices und des AWS Well-Architected Framework. Die Bewertung empfiehlt außerdem Verbesserungen und Korrekturen.

Die gut strukturierte Analyse kategorisiert Konfigurationen in den folgenden Säulen des Rahmenwerks: _Zuverlässigkeit_, _Sicherheit_, _operative Exzellenz_, _Kostenoptimierung_ und _Leistungseffizienz_.



[[reliability]]
=== Zuverlässigkeit

Zuverlässigkeit gewährleistet, dass Arbeitslasten ihre beabsichtigten Funktionen korrekt und konsistent erfüllen, selbst wenn es zu Störungen kommt.

* *Volume-Backups planen*
+
Die Sicherung Ihrer Volumes unterstützt die Einhaltung von Aufbewahrungs- und Compliance-Anforderungen. Verwenden Sie Volume-Backups, um automatisierte Backups und Aufbewahrung für Ihre Daten einzurichten.

* *Lokale Snapshots planen*
+
Planen Sie lokale Snapshots für effiziente Datensicherung und schnelle Wiederherstellung. Snapshots sind sofortige, zeitpunktgenaue Abbilder Ihrer Volumes.

* *Regionenübergreifende Replikation*
+
Die regionsübergreifende Replikation stellt sicher, dass Ihre Daten in eine andere AWS-Region repliziert werden und bietet so eine verbesserte Datenbeständigkeit und Verfügbarkeit. Workload Factory empfiehlt die Einrichtung der regionsübergreifenden Replikation, um bei der Notfallwiederherstellung und Compliance zu unterstützen.

* *Datenreplizierung*
+
Um die Datenzuverlässigkeit zu erhöhen, können Daten auf ein FSx for ONTAP-Dateisystem in derselben Region oder in einer anderen Region repliziert werden. Richten Sie Datenreplizierung ein, um Migration, Notfallwiederherstellung und langfristige Aufbewahrung über verschiedene Dateisysteme hinweg zu unterstützen.

* *SSD-Kapazitätsschwelle erhöhen*
+
Die SSD-Speicherebene sollte eine Auslastung von 80 % nicht überschreiten. Dies kann sich auf Lese- und Schreibvorgänge auf Ihrer Kapazitätspool-Speicherebene auswirken und die Durchsatzkapazität Ihres Dateisystems beeinträchtigen. Ein Kapazitätsmangel führt dazu, dass Datenvolumes nur noch lesbar sind. Dienste, die versuchen, neue Daten zu schreiben, schlagen ebenfalls fehl.

* *Beschriftungen abgleichen, um die Datenzuverlässigkeit sicherzustellen*
+
Die Snapshot-Richtlinienbezeichnungen des Quellvolumes und die Replikationsrichtlinienbezeichnungen müssen übereinstimmen, um die Datenzuverlässigkeit zu gewährleisten.

* *Dateikapazitätsschwelle erhöhen*
+
Um die Kapazitätsgrenze des Volumes nicht zu erreichen, sollte der Schwellenwert für die Dateikapazität erhöht werden. Eine geringe Dateikapazität (Inodes) verhindert das Schreiben weiterer Daten auf das Volume. Workload Factory empfiehlt, die Kapazitätsauslastung der Dateikapazität unter 80 % zu halten. Verfügbare Dateikapazität wird benötigt, um neue Dateien im Volume zu erstellen.





[[security]]
=== Sicherheit

Sicherheit betont den Schutz von Daten, Systemen und Vermögenswerten durch Risikobewertungen und Risikominderungsstrategien.

* *ARP/AI aktivieren*
+
NetApp Autonomous Ransomware Protection mit KI (ARP/AI) hilft, Ihre Volumes vor Ransomware-Bedrohungen zu schützen. Workload Factory empfiehlt, ARP/AI für alle Volumes zu aktivieren.

* *Unbefugter Zugriff auf Volumes*
+
Volumes, die Anwendungsdaten über iSCSI bereitstellen, sollten nicht gleichzeitig NAS-Zugriff ermöglichen. Workload Factory empfiehlt, iSCSI-Volumes von der Verwendung anderer Protokolle auszuschließen.





[[operational-excellence]]
=== Operative Exzellenz

Operative Exzellenz konzentriert sich auf die Bereitstellung der optimalsten Architektur und des größten Geschäftswerts.

* *Automatisches Kapazitätsmanagement aktivieren*
+
Automatisches Kapazitätsmanagement sollte aktiviert werden, um regelmäßig sicherzustellen, dass die SSD-Ebene den Schwellenwert nicht überschreitet.

* *Kapazitätsauslastungsschwellenwert*
+
Workload Factory empfiehlt, dass die Volume-Kapazität die Kapazitätsauslastung von 80 % auf fortlaufender Basis nicht überschreitet. Dies kann sich auf das Lesen und Schreiben von Daten in Ihrer Anwendung auswirken. Volume-Kapazitätserhöhungen können manuell oder automatisch mithilfe der Volume-Autogrow-Funktion erfolgen.

* *Volumenauslastung nähert sich der Vollauslastung*
+
Wenn ein Volume sich der vollen Kapazität nähert, empfiehlt Workload Factory, Maßnahmen zu ergreifen, um die Volume-Kapazität zu erhöhen und potenzielle Anwendungsunterbrechungen zu vermeiden.

* *Schreibmodus für Cache-Beziehungen*
+
Für optimale Leistung empfiehlt Workload Factory den Cache-Beziehungs-Schreibmodus, der am besten zu Ihrer Arbeitslast passt. Der Write-Around-Modus bietet eine bessere Leistung für leseintensive Arbeitslasten mit kleinen Dateien, während der Write-Back-Modus eine bessere Leistung für schreibintensive Arbeitslasten mit großen Dateien bietet.

* *Cache-Volume-Größe optimieren*
+
Workload Factory empfiehlt, die automatische Größenanpassung und das Scrubbing auf Cache-Volumes zu aktivieren, um eine optimale Größe beizubehalten und den Cache auf Hot Data für maximale Effizienz zu fokussieren.

* *Logische Berichterstellung für Storage-VMs*
+
Workload Factory empfiehlt, dass die Standardeinstellung für die Berichtserstellung für eine Speicher-VM auf logisch gesetzt wird, um eine bessere Sichtbarkeit der Speichernutzung auf Volume-Ebene zu bieten.





[[cost-optimization]]
=== Kostenoptimierung

Kostenoptimierung hilft Ihnen, den größtmöglichen Nutzen für Ihr Unternehmen zu erzielen und gleichzeitig die Kosten niedrig zu halten.

* *Optimieren Sie die Gesamtbetriebskosten durch das Tiering von Kaltdaten*
+
Die Aktivierung der Tiering-Funktion für kalte Daten reduziert die Auslastung der SSD-Speicherebene. Workload Factory empfiehlt, auf jedes Volume eine Tiering-Richtlinie anzuwenden. FSx for ONTAP scannt die Daten kontinuierlich, um kalte Daten zu erkennen und sie ohne Unterbrechung in die Kapazitäts-Speicherebene zu verschieben.

* *Speichereffizienzen aktivieren*
+
Speichereffizienzmaßnahmen wie Verdichtung, Komprimierung und Deduplizierung ermöglichen eine optimierte Speicherauslastung und eine Reduzierung der Kosten der SSD-Ebene.

* *Unnötige Snapshot- und Backup-Löschung*
+
Snapshots und Backups, die nicht mehr benötigt werden, sollten gelöscht werden, um Kosten zu reduzieren.

* *Inaktive Blockgeräte*
+
Nachdem ein Blockgerät sieben Tage lang nicht verwendet wurde, empfiehlt Workload Factory, die Blockgerätedaten zu archivieren oder das ungenutzte Blockgerät zu löschen, um Kosten zu senken.

* *Nicht ausgelastete SSD-Kapazität*
+
Eine nicht voll ausgelastete SSD-Kapazitätsebene verursacht unnötige Kosten. Workload Factory empfiehlt, die SSD-Kapazitätsebene zu reduzieren, wobei ein freier Speicherpuffer von 20 % über der aktuell genutzten Kapazität beibehalten wird. Eine Verringerung kann mehrere Stunden bis mehrere Tage dauern, und das System unterstützt während dieser Zeit keine anderen Dateisystemoperationen.

* *Inaktive NAS-Volumes*
+
Die Konfigurationsanalyse identifiziert NAS-Volumes, die nicht aktiv genutzt werden, und empfiehlt, die Volumes zu löschen oder zu archivieren, um Kosten zu reduzieren.



.Was kommt als Nächstes
link:improve-configurations-fsx.html["Gut strukturierte FSx for ONTAP Dateisystemkonfigurationen implementieren"]
