---
sidebar: sidebar 
permalink: fsx/configuration-analysis-fsx.html 
keywords: configuration issues, issues, improve, analyze, storage configuration, recommendation, recommendations 
summary: Das gut strukturierte Dashboard analysiert regelmäßig die Dateisystemkonfigurationen von FSx for ONTAP, um festzustellen, ob Konfigurationsprobleme vorliegen. 
---
= Konfigurationsanalyse für Amazon FSx für NetApp ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Das gut strukturierte Dashboard in der NetApp Console analysiert regelmäßig die Konfigurationen der Speichersysteme, um festzustellen, ob Konfigurationsprobleme mit Ihren Amazon FSx for NetApp ONTAP Dateisystemen vorliegen. Wenn Probleme festgestellt werden, zeigt das Dashboard an, welche Probleme bestehen, und erläutert, welche Änderungen erforderlich sind, damit Ihre Speichersysteme Spitzenleistung, Kosteneffizienz und die Einhaltung bewährter Verfahren erreichen.

Zu den wichtigsten Fähigkeiten gehören:

* Tägliche Konfigurationsanalyse
* Automatische Validierung bewährter Verfahren für NetApp ONTAP Speichersysteme und Partner-Speicheranbieter
* Proaktive Beobachtbarkeit
* Erkenntnisse in die Praxis umsetzen




[[analysis-requirements]]
== Analyseanforderungen

Für eine vollständige Dateisystemanalyse sind die folgenden Schritte erforderlich:

* link:https://docs.netapp.com/us-en/console-setup-admin/concept-agent-install-options.html#agent-console-deploy["Einen NetApp Console-Agenten bereitstellen"^] oder link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["einen Link verknüpfen"^] zur Einrichtung der Konnektivität zwischen dem Dateisystem und der NetApp Console.
* Gewähren Sie _view, planning, and analysis_-Berechtigungen in Ihrem AWS-Konto.
+
link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["Erfahren Sie, wie Sie einem AWS-Konto Berechtigungen erteilen"^]





[[best-practices-and-recommendations-for-storage-workloads]]
== Bewährte Verfahren und Empfehlungen für Speicher-Workloads

Das gut strukturierte Dashboard bewertet Speicherkonfigurationen anhand der ONTAP Best Practices und des AWS Well-Architected Framework. Die Bewertung enthält außerdem Empfehlungen für Verbesserungen und Fehlerbehebungen.

Die gut strukturierte Analyse kategorisiert Konfigurationen in den folgenden Säulen des Rahmenwerks: _Zuverlässigkeit_, _Sicherheit_, _operative Exzellenz_, _Kostenoptimierung_ und _Leistungseffizienz_.



[[reliability]]
=== Zuverlässigkeit

Zuverlässigkeit gewährleistet, dass Arbeitslasten ihre beabsichtigten Funktionen korrekt und konsistent erfüllen, selbst wenn es zu Störungen kommt.

* *Volume-Backups planen*
+
Die Sicherung Ihrer Volumes unterstützt die Einhaltung von Aufbewahrungs- und Compliance-Anforderungen. Verwenden Sie Volume-Backups, um automatisierte Backups und Aufbewahrung für Ihre Daten einzurichten.

* *Lokale Snapshots planen*
+
Planen Sie lokale Snapshots für effiziente Datensicherung und schnelle Wiederherstellung. Snapshots sind sofortige, zeitpunktgenaue Abbilder Ihrer Volumes.

* *Regionenübergreifende Replikation*
+
Die regionsübergreifende Replikation stellt sicher, dass Ihre Daten in eine andere AWS-Region repliziert werden, was eine erhöhte Datenbeständigkeit und Verfügbarkeit bietet. Die Einrichtung der regionsübergreifenden Replikation unterstützt Notfallwiederherstellung und Compliance.

* *Datenreplizierung*
+
Um die Datenzuverlässigkeit zu erhöhen, werden Daten auf ein FSx for ONTAP Dateisystem in derselben Region oder in einer anderen Region repliziert. Datenreplizierung wird eingerichtet, um Migration, Notfallwiederherstellung und langfristige Aufbewahrung über Dateisysteme hinweg zu unterstützen.

* *SSD-Kapazitätsschwelle erhöhen*
+
Die SSD-Speicherebene sollte eine Kapazitätsauslastung von maximal 80 % nicht überschreiten. Dies kann sich auf Lese- und Schreibvorgänge auf Ihrer Kapazitätspool-Speicherebene auswirken und die Durchsatzkapazität Ihres Dateisystems beeinträchtigen. Wenn die Kapazität erschöpft ist, werden Datenvolumes schreibgeschützt. Dienste, die versuchen, neue Daten zu schreiben, schlagen ebenfalls fehl.

* *Beschriftungen abgleichen, um die Datenzuverlässigkeit sicherzustellen*
+
Die Snapshot-Richtlinienbezeichnungen des Quellvolumes und die Replikationsrichtlinienbezeichnungen müssen übereinstimmen, um die Datenzuverlässigkeit zu gewährleisten.

* *Dateikapazitätsschwelle erhöhen*
+
Um die Speicherkapazitätsgrenze des Volumes nicht zu erreichen, sollte der Schwellenwert für die Dateikapazität erhöht werden. Eine geringe Dateikapazität (Inodes) verhindert das Schreiben weiterer Daten auf das Volume. Workload Factory empfiehlt, die Dateikapazitätsauslastung unter 80 % zu halten, um die Erstellung neuer Dateien zu ermöglichen.





[[security]]
=== Sicherheit

Sicherheit betont den Schutz von Daten, Systemen und Vermögenswerten durch Risikobewertungen und Risikominderungsstrategien.

* *ARP/AI aktivieren*
+
NetApp Autonomous Ransomware Protection mit KI (ARP/AI) hilft, Ihre Volumes vor Ransomware-Bedrohungen zu schützen. Workload Factory empfiehlt, ARP/AI für alle Volumes zu aktivieren.

* *Unbefugter Zugriff auf Volumes*
+
Volumes, die Anwendungsdaten über iSCSI bereitstellen, sollten nicht gleichzeitig NAS-Zugriff ermöglichen. Workload Factory empfiehlt, iSCSI-Volumes von der Verwendung anderer Protokolle auszuschließen.





[[operational-excellence]]
=== Operative Exzellenz

Operative Exzellenz konzentriert sich auf die Bereitstellung der optimalsten Architektur und des größten Geschäftswerts.

* *Automatisches Kapazitätsmanagement aktivieren*
+
Automatisches Kapazitätsmanagement sollte aktiviert werden, um regelmäßig sicherzustellen, dass die SSD-Ebene den Schwellenwert nicht überschreitet.

* *Kapazitätsauslastungsschwellenwert*
+
Workload Factory empfiehlt, dass die Volume-Kapazität die 80%ige Kapazitätsauslastung nicht überschreitet. Dies kann sich auf Lese- und Schreibvorgänge Ihrer Anwendung auswirken. Volume-Kapazitätserhöhungen können manuell oder automatisch mithilfe der Volume Autogrow-Funktion erfolgen.

* *Volumenauslastung nähert sich der Vollauslastung*
+
Wenn ein Volume sich der vollen Kapazität nähert, empfiehlt Workload Factory, Maßnahmen zu ergreifen, um die Volume-Kapazität zu erhöhen und potenzielle Anwendungsunterbrechungen zu vermeiden.

* *Schreibmodus für Cache-Beziehungen*
+
Für optimale Leistung empfiehlt Workload Factory den Cache-Beziehungs-Schreibmodus, der am besten zu Ihrer Arbeitslast passt. Der Write-Around-Modus bietet eine bessere Leistung für leseintensive Arbeitslasten mit kleinen Dateien, während der Write-Back-Modus eine bessere Leistung für schreibintensive Arbeitslasten mit großen Dateien bietet.

* *Cache-Volume-Größe optimieren*
+
Workload Factory empfiehlt, die automatische Größenanpassung und das Scrubbing auf Cache-Volumes zu aktivieren, um eine optimale Größe beizubehalten und den Cache auf Hot Data für maximale Effizienz zu fokussieren.

* *Logische Berichterstellung für Storage-VMs*
+
Workload Factory empfiehlt, dass die Standardeinstellung für die Berichtserstellung für eine Speicher-VM auf logisch gesetzt wird, um eine bessere Sichtbarkeit der Speichernutzung auf Volume-Ebene zu bieten.





[[cost-optimization]]
=== Kostenoptimierung

Kostenoptimierung hilft Ihnen, den größtmöglichen Nutzen für Ihr Unternehmen zu erzielen und gleichzeitig die Kosten niedrig zu halten.

* *Optimieren Sie die Gesamtbetriebskosten durch das Tiering von Kaltdaten*
+
Aktivieren Sie das Tiering kalter Daten, um die Auslastung der SSD-Speicherebene zu reduzieren. Workload Factory empfiehlt, auf jedes Volume eine Tiering-Richtlinie anzuwenden. FSx for ONTAP scannt die Daten kontinuierlich nach kalten Daten und verschiebt sie ohne Unterbrechung in die Kapazitätspoolebene.

* *Speichereffizienzen aktivieren*
+
Speichereffizienzmaßnahmen wie Verdichtung, Komprimierung und Deduplizierung ermöglichen eine optimierte Speicherauslastung und eine Reduzierung der Kosten der SSD-Ebene.

* *Unnötige Snapshot- und Backup-Löschung*
+
Snapshots und Backups, die nicht mehr benötigt werden, löschen, um Kosten zu senken.

* *Inaktive Blockgeräte*
+
Nachdem ein Blockgerät sieben Tage lang nicht verwendet wurde, empfiehlt Workload Factory, die Blockgerätedaten zu archivieren oder das ungenutzte Blockgerät zu löschen, um Kosten zu senken.

* *Nicht ausgelastete SSD-Kapazität*
+
Eine unzureichend ausgelastete SSD-Kapazitätsebene verursacht unnötige Kosten. Workload Factory empfiehlt, die SSD-Kapazitätsebene zu reduzieren und dabei einen freien Speicherpuffer von 20 % beizubehalten. Eine Verringerung dauert mehrere Stunden bis mehrere Tage, und andere Dateisystemoperationen werden in dieser Zeit nicht unterstützt.

* *Inaktive NAS-Volumes*
+
Die Konfigurationsanalyse identifiziert NAS-Volumes, die nicht aktiv genutzt werden, und empfiehlt, die Volumes zu löschen oder zu archivieren, um Kosten zu reduzieren.



.Was kommt als Nächstes
link:improve-configurations-fsx.html["Gut strukturierte FSx for ONTAP Dateisystemkonfigurationen implementieren"]
